# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
       teceng_user_provider:
           entity:
               class: AppBundle:Document:User
               property: username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        login_firewall:
            pattern:   ^/login$
            anonymous: ~
            
        default:
            pattern:    ^/login
            http_basic: ~
            provider: teceng_user_provider
            form_login:
                login_path: /login
                check_path: /login_check 
                default_target_path: main_index    
                csrf_provider: form.csrf_provider
                failure_handler: core.authentication_handler
                success_handler: core.authentication_handler                
            logout:  
                path: /logout
                target: / 
                success_handler: core.logout_handler
 
        
        
   
  