services:
    security_listener:
        class: AppBundle\Listener\SecurityListener
        arguments: ['@security.context','@doctrine.orm.entity_manager'  ,'@event_dispatcher' , '@router' ]
        tags:
           - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }

    core.authentication_handler:
        class: AppBundle\Security\Authentication\Handler\AuthenticationHandler
        arguments: [ @security.authentication_utils,  @router, @translator.default]
        
    core.logout_handler:
        class: AppBundle\Security\Http\Logout\Handler\LogoutHandler
        arguments: [@doctrine.orm.entity_manager, @router, @security.context]

