services:


    core.authentication_handler:
        class: Core\CommonBundle\Security\Authentication\Handler\AuthenticationHandler
        arguments: [@core.authentication_error_log, @security.authentication_utils, @core.locked_user_log, @router, @translator.default]


    core.authentication_error_log:
          class: AppBundle\Security\Authentication\Manager\AuthenticationErrorLogManager
          arguments: [@core.global_parameter, @doctrine.orm.entity_manager, @core.locked_user_log]

    core.locked_user_log:
        class: AppBundle\Security\Authentication\Manager\LockedUserLogManager
        arguments: [@doctrine.orm.entity_manager]
        
    core.logout_handler:
        class: AppBundle\Security\Http\Logout\Handler\LogoutHandler
        arguments: [@doctrine.orm.entity_manager, @router, @security.context]

    core.listener.before_controller:
        class: AppBundle\Listener\BeforeControllerListener
        arguments: ['@security.context']
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
#            